// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrrhjC2YghhNjMPJhUZ9L3kmEZap9yL6w',
    appId: '1:11178644691:web:6b0a2c473489331da0b026',
    messagingSenderId: '11178644691',
    projectId: 'smart-app-flutter-8acf7',
    authDomain: 'smart-app-flutter-8acf7.firebaseapp.com',
    storageBucket: 'smart-app-flutter-8acf7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2XZOYGxZPey7D-BOjKCj6na5BQAS7xxk',
    appId: '1:11178644691:android:df1cbaf3cd41d0d1a0b026',
    messagingSenderId: '11178644691',
    projectId: 'smart-app-flutter-8acf7',
    storageBucket: 'smart-app-flutter-8acf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPfD0aheWA5K9-sagR26EtAUGvAiGvkqU',
    appId: '1:11178644691:ios:43e9ed5a0ae52ae0a0b026',
    messagingSenderId: '11178644691',
    projectId: 'smart-app-flutter-8acf7',
    storageBucket: 'smart-app-flutter-8acf7.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPfD0aheWA5K9-sagR26EtAUGvAiGvkqU',
    appId: '1:11178644691:ios:43e9ed5a0ae52ae0a0b026',
    messagingSenderId: '11178644691',
    projectId: 'smart-app-flutter-8acf7',
    storageBucket: 'smart-app-flutter-8acf7.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrrhjC2YghhNjMPJhUZ9L3kmEZap9yL6w',
    appId: '1:11178644691:web:18e684379622327ca0b026',
    messagingSenderId: '11178644691',
    projectId: 'smart-app-flutter-8acf7',
    authDomain: 'smart-app-flutter-8acf7.firebaseapp.com',
    storageBucket: 'smart-app-flutter-8acf7.firebasestorage.app',
  );

}